### PR TITLE
fixing library

### PR DESCRIPTION
**Pull request by KostSvitlana**
- fix sanic's using
- fix tox.ini file
- fix examples
- fix flake8

### CODE REVIEW

**Comment by digitalkaoz** [comment]
can we get a merge+release on this?

**Comment by digitalkaoz** [comment]
works like a charm with the latest sanic!

**Comment by digitalkaoz** [comment]
ping @MihaiBalint

**Comment by MihaiBalint** [comment]
Wow, when did this happen? Thanks for the ping!

**Comment by MihaiBalint** [comment]
@KostSvitlana @digitalkaoz I've published 0.2.0 with your updates on pypi - https://pypi.org/project/Sanic-HTTPAuth/

Many thanks for your contribution!

**Comment by digitalkaoz** [comment]
Thank you very much!

**Comment by KostSvitlana** [comment]
Thanks for the quick reply.

**Pull request merged**
